export const Languages = [
  {code: 'ar-SA', name: 'Arabic (Saudi Arabia)', translateCode: 'ar'},
  {code: 'zh-HK', name: 'Chinese (Hong Kong S.A.R.)', translateCode: 'zh-TW'},
  {
    code: 'zh-CN',
    name: "Chinese (People's Republic of China)",
    translateCode: 'zh-CN',
  },
  {code: 'zh-TW', name: 'Chinese (Taiwan)', translateCode: 'zh-TW'},
  {code: 'cs-CZ', name: 'Czech (Czech Republic)', translateCode: 'cs'},
  {code: 'da-DK', name: 'Danish (Denmark)', translateCode: 'da'},
  {code: 'nl-BE', name: 'Dutch (Belgium)', translateCode: 'nl'},
  {code: 'nl-NL', name: 'Dutch (Netherlands)', translateCode: 'nl'},
  {code: 'en', name: 'English', translateCode: 'en'},
  {code: 'en-AU', name: 'English (Australia)', translateCode: 'en'},
  {code: 'en-IN', name: 'English (India)', translateCode: 'en'},
  {code: 'en-IE', name: 'English (Ireland)', translateCode: 'en'},
  {code: 'en-ZA', name: 'English (South Africa)', translateCode: 'en'},
  {code: 'en-GB', name: 'English (United Kingdom)', translateCode: 'en'},
  {code: 'en-US', name: 'English (United States)', translateCode: 'en'},
  {code: 'fi-FI', name: 'Finnish (Finland)', translateCode: 'fi'},
  {code: 'fr-CA', name: 'French (Canada)', translateCode: 'fr'},
  {code: 'fr-FR', name: 'French (France)', translateCode: 'fr'},
  {code: 'de-DE', name: 'German (Germany)', translateCode: 'de'},
  {code: 'el-GR', name: 'Greek (Greece)', translateCode: 'el'},
  {code: 'he-IL', name: 'Hebrew (Israel)', translateCode: 'he'},
  {code: 'hi-IN', name: 'Hindi (India)', translateCode: 'hi'},
  {code: 'hu-HU', name: 'Hungarian (Hungary)', translateCode: 'hu'},
  {code: 'id-ID', name: 'Indonesian (Indonesia)', translateCode: 'id'},
  {code: 'it-IT', name: 'Italian (Italy)', translateCode: 'it'},
  {code: 'ja-JP', name: 'Japanese (Japan)', translateCode: 'ja'},
  {code: 'ko-KR', name: 'Korean (Korea)', translateCode: 'ko'},
  {code: 'nb-NO', name: 'Norwegian, Bokmål (Norway)', translateCode: 'no'},
  {code: 'pl-PL', name: 'Polish (Poland)', translateCode: 'pl'},
  {code: 'pt-BR', name: 'Portuguese (Brazil)', translateCode: 'pt'},
  {code: 'pt-PT', name: 'Portuguese (Portugal)', translateCode: 'pt'},
  {code: 'ro-RO', name: 'Romanian (Romania)', translateCode: 'ro'},
  {code: 'ru-RU', name: 'Russian (Russia)', translateCode: 'ru'},
  {code: 'sk-SK', name: 'Slovak (Slovakia)', translateCode: 'sk'},
  {code: 'es-AR', name: 'Spanish (Argentina)', translateCode: 'es'},
  {code: 'es-MX', name: 'Spanish (Mexico)', translateCode: 'es'},
  {code: 'es-ES', name: 'Spanish (Spain)', translateCode: 'es'},
  {code: 'es-US', name: 'Spanish (United States)', translateCode: 'es'},
  {code: 'sv-SE', name: 'Swedish (Sweden)', translateCode: 'sv'},
  {code: 'th-TH', name: 'Thai (Thailand)', translateCode: 'th'},
  {code: 'tr-TR', name: 'Turkish (Turkey)', translateCode: 'tr'},
];
